# Generated by Django 5.0.6 on 2026-04-24 22:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.CharField(default='box-seam', help_text='Nome do ícone Bootstrap Icons (ex: box-seam, pencil, printer)', max_length=50, verbose_name='Ícone Bootstrap Icons')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome / Razão Social')),
                ('cnpj', models.CharField(blank=True, help_text='Formato: XX.XXX.XXX/XXXX-XX', max_length=18, verbose_name='CNPJ')),
                ('contato', models.CharField(blank=True, help_text='Telefone ou e-mail de contato', max_length=200, verbose_name='Contato')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('matricula', models.CharField(help_text='Matrícula SIAPE do servidor', max_length=20, unique=True, verbose_name='Matrícula SIAPE')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail institucional')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('is_ativo', models.BooleanField(default=True, help_text='Desmarque para desativar o acesso do servidor ao sistema', verbose_name='Ativo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['nome_completo'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Almoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do almoxarifado')),
                ('localizacao', models.CharField(help_text='Ex: Bloco A, Sala 102', max_length=200, verbose_name='Localização')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifados_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Almoxarifado',
                'verbose_name_plural': 'Almoxarifados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do item')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('unidade_medida', models.CharField(choices=[('un', 'Unidade'), ('cx', 'Caixa'), ('rs', 'Resma'), ('lt', 'Litro'), ('kg', 'Quilograma'), ('m', 'Metro'), ('pc', 'Pacote')], default='un', max_length=2, verbose_name='Unidade de medida')),
                ('quantidade_atual', models.IntegerField(default=0, verbose_name='Quantidade atual')),
                ('quantidade_minima', models.IntegerField(default=0, help_text='Abaixo desse valor, o item será marcado como estoque baixo', verbose_name='Quantidade mínima')),
                ('codigo_interno', models.CharField(blank=True, help_text='Gerado automaticamente', max_length=20, unique=True, verbose_name='Código interno')),
                ('localizacao_fisica', models.CharField(blank=True, help_text='Ex: Prateleira B, Coluna 3', max_length=100, verbose_name='Localização física')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('almoxarifado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='estoque.almoxarifado', verbose_name='Almoxarifado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='estoque.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste'), ('TRANSFERENCIA', 'Transferência')], max_length=15, verbose_name='Tipo de movimentação')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('quantidade_anterior', models.IntegerField(editable=False, verbose_name='Quantidade anterior')),
                ('quantidade_posterior', models.IntegerField(editable=False, verbose_name='Quantidade posterior')),
                ('destino_origem', models.CharField(blank=True, help_text='Para quem saiu o material ou de onde veio', max_length=200, verbose_name='Destino / Origem')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da movimentação')),
                ('almoxarifado', models.ForeignKey(help_text='Preenchido automaticamente a partir do item', on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.almoxarifado', verbose_name='Almoxarifado')),
                ('almoxarifado_destino', models.ForeignKey(blank=True, help_text='Usado apenas em transferências', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recebidas', to='estoque.almoxarifado', verbose_name='Almoxarifado de destino')),
                ('fornecedor', models.ForeignKey(blank=True, help_text='Usado apenas em entradas', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.fornecedor', verbose_name='Fornecedor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.item', verbose_name='Item')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo registro')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
