# Generated by Django 5.0.6 on 2026-04-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='destino_origem',
        ),
        migrations.AddField(
            model_name='item',
            name='anexo',
            field=models.FileField(blank=True, help_text='Nota fiscal, manual, FISPQ, foto do item (PDF ou imagem)', null=True, upload_to='itens/anexos/%Y/%m/', verbose_name='Anexo'),
        ),
        migrations.AddField(
            model_name='item',
            name='codigo_patrimonio',
            field=models.CharField(blank=True, help_text='Número de tombamento patrimonial', max_length=50, verbose_name='Código de patrimônio'),
        ),
        migrations.AddField(
            model_name='item',
            name='data_fabricacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de fabricação'),
        ),
        migrations.AddField(
            model_name='item',
            name='data_validade',
            field=models.DateField(blank=True, help_text='Para reagentes e materiais perecíveis', null=True, verbose_name='Data de validade'),
        ),
        migrations.AddField(
            model_name='item',
            name='lote',
            field=models.CharField(blank=True, help_text='Número do lote de fabricação', max_length=100, verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='item',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor de aquisição por unidade', max_digits=10, null=True, verbose_name='Valor unitário (R$)'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='solicitante_departamento',
            field=models.CharField(blank=True, help_text='Ex: Geologia, Análise Geoambiental, Geografia', max_length=100, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='solicitante_nome',
            field=models.CharField(blank=True, help_text='Para quem foi destinado (em caso de saída)', max_length=200, verbose_name='Nome do solicitante'),
        ),
    ]
