# Generated by Django 5.0.6 on 2026-04-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_remove_movimentacao_destino_origem_item_anexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unidade_medida',
            field=models.CharField(choices=[('un', 'Unidade'), ('cx', 'Caixa'), ('rs', 'Resma'), ('lt', 'Litro'), ('kg', 'Quilograma'), ('m', 'Metro'), ('pc', 'Pacote'), ('ou', 'Outros')], default='un', max_length=2, verbose_name='Unidade de medida'),
        ),
    ]
