# Generated by Django 5.0.6 on 2026-04-28 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_item_unidade_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='item',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='estoque.fornecedor', verbose_name='Fornecedor padrão'),
        ),
    ]
