# Generated by Django 5.0.6 on 2026-04-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_remove_movimentacao_fornecedor_item_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, default='box-seam', help_text='Nome do ícone Bootstrap Icons', max_length=50, verbose_name='Ícone Bootstrap Icons'),
        ),
    ]
