# Generated by Django 5.0.6 on 2026-05-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_categoria_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='nf_data_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de emissão da NF'),
        ),
        migrations.AddField(
            model_name='item',
            name='nf_data_entrada',
            field=models.DateField(blank=True, help_text='Data em que o material foi recebido no almoxarifado', null=True, verbose_name='Data de entrada (recebimento)'),
        ),
        migrations.AddField(
            model_name='item',
            name='nf_numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número da NF'),
        ),
        migrations.AddField(
            model_name='item',
            name='nf_serie',
            field=models.CharField(blank=True, max_length=10, verbose_name='Série da NF'),
        ),
        migrations.AddField(
            model_name='item',
            name='nf_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor total da NF (R$)'),
        ),
        migrations.AddField(
            model_name='item',
            name='numero_empenho',
            field=models.CharField(blank=True, help_text='Ex: 2024NE000123', max_length=50, verbose_name='Número do empenho'),
        ),
        migrations.AddField(
            model_name='item',
            name='processo_sei',
            field=models.CharField(blank=True, help_text='Número do processo no SEI/UFF (ex: 23069.000123/2024-12)', max_length=50, verbose_name='Processo SEI'),
        ),
        migrations.AddField(
            model_name='item',
            name='tipo_empenho',
            field=models.CharField(blank=True, choices=[('', '—'), ('ORDINARIO', 'Ordinário'), ('ESTIMATIVO', 'Estimativo'), ('GLOBAL', 'Global')], max_length=15, verbose_name='Tipo de empenho'),
        ),
        migrations.AddField(
            model_name='item',
            name='tipo_material',
            field=models.CharField(choices=[('CONSUMO', 'Material de Consumo'), ('PERMANENTE', 'Bem Permanente')], default='CONSUMO', help_text='Material de Consumo (uso/desgaste) ou Bem Permanente (durável)', max_length=15, verbose_name='Tipo de material'),
        ),
    ]
