# Generated by Django 5.0.6 on 2026-05-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_item_nf_data_emissao_item_nf_data_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='matricula',
        ),
    ]
