# Generated by Django 5.0.6 on 2026-05-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_remove_usuario_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('DESCARTE', 'Descarte'), ('AJUSTE', 'Ajuste'), ('TRANSFERENCIA', 'Transferência')], max_length=15, verbose_name='Tipo de movimentação'),
        ),
    ]
