# Generated by Django 5.0.6 on 2026-08-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_alter_movimentacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('ADMIN', 'Administrador — acesso total, gerencia usuários'), ('GESTOR', 'Gestor — cadastra e movimenta, não edita/exclui nem gerencia usuários'), ('OPERADOR', 'Operador — apenas registra movimentações (entrada/saída)')], default='OPERADOR', max_length=10, verbose_name='Nível de acesso'),
        ),
    ]
